// AUTO-GENERATED FILE. DO NOT EDIT.
// Run scripts/generateContractTypes.ts to update.

export type DealProviderFunctionName =
  | 'acceptFirewallAdmin'
  | 'createNewPool'
  | 'currentParamsTargetLength'
  | 'firewallAdmin'
  | 'getParams'
  | 'getSubProvidersPoolIds'
  | 'getWithdrawableAmount'
  | 'lockDealNFT'
  | 'name'
  | 'poolIdToAmount'
  | 'registerPool'
  | 'safeFunctionCall'
  | 'setApprovedVennPolicy'
  | 'setApprovedVennPolicyFee'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'split'
  | 'supportsInterface'
  | 'withdraw';

export type DispenserProviderFunctionName =
  | 'BUILDER_TYPEHASH'
  | 'MESSAGE_TYPEHASH'
  | 'acceptFirewallAdmin'
  | 'createNewPool'
  | 'currentParamsTargetLength'
  | 'dispenseLock'
  | 'eip712Domain'
  | 'firewallAdmin'
  | 'getParams'
  | 'getSubProvidersPoolIds'
  | 'getWithdrawableAmount'
  | 'isTaken'
  | 'lockDealNFT'
  | 'name'
  | 'poolIdToAmount'
  | 'registerPool'
  | 'safeFunctionCall'
  | 'setApprovedVennPolicy'
  | 'setApprovedVennPolicyFee'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'split'
  | 'supportsInterface'
  | 'withdraw';

export type ForceWithdrawFunctionName =
  | 'createPool'
  | 'dealProvider'
  | 'finilize'
  | 'forceWithdraw'
  | 'lockDealNFT'
  | 'onERC721Received'
  | 'owner'
  | 'renounceOwnership'
  | 'sourcePoolId'
  | 'token'
  | 'transferOwnership'
  | 'transferTokens'
  | 'vaultId'
  | 'vaultManager'
  | 'withdrawNFT';

export type InvestProviderFunctionName =
  | 'INVEST_TYPEHASH'
  | 'acceptFirewallAdmin'
  | 'createNewPool'
  | 'currentParamsTargetLength'
  | 'dispenserProvider'
  | 'eip712Domain'
  | 'firewallAdmin'
  | 'getNonce'
  | 'getParams'
  | 'getSubProvidersPoolIds'
  | 'getUserInvests'
  | 'getWithdrawableAmount'
  | 'invest'
  | 'lockDealNFT'
  | 'name'
  | 'poolIdToInvests'
  | 'poolIdToPool'
  | 'registerPool'
  | 'safeFunctionCall'
  | 'setApprovedVennPolicy'
  | 'setApprovedVennPolicyFee'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'split'
  | 'supportsInterface'
  | 'vaultManager'
  | 'withdraw';

export type LockDealNFTFunctionName =
  | 'acceptFirewallAdmin'
  | 'approve'
  | 'approvePoolTransfers'
  | 'approvedContracts'
  | 'approvedPoolUserTransfers'
  | 'balanceOf'
  | 'baseURI'
  | 'cloneVaultId'
  | 'firewallAdmin'
  | 'getApproved'
  | 'getData'
  | 'getFullData'
  | 'getUserDataByTokens'
  | 'getWithdrawableAmount'
  | 'isApprovedForAll'
  | 'mintAndTransfer'
  | 'mintForProvider'
  | 'name'
  | 'onERC721Received'
  | 'owner'
  | 'ownerOf'
  | 'poolIdToProvider'
  | 'poolIdToVaultId'
  | 'renounceOwnership'
  | 'royaltyInfo'
  | 'safeFunctionCall'
  | 'safeMintAndTransfer'
  | 'safeTransferFrom'
  | 'setApprovalForAll'
  | 'setApprovedContract'
  | 'setApprovedTarget'
  | 'setBaseURI'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'supportsInterface'
  | 'symbol'
  | 'tokenByIndex'
  | 'tokenOf'
  | 'tokenOfOwnerByIndex'
  | 'tokenURI'
  | 'totalSupply'
  | 'transferFrom'
  | 'transferOwnership'
  | 'updateAllMetadata'
  | 'vaultManager';

export type LockDealProviderFunctionName =
  | 'acceptFirewallAdmin'
  | 'createNewPool'
  | 'currentParamsTargetLength'
  | 'firewallAdmin'
  | 'getParams'
  | 'getSubProvidersPoolIds'
  | 'getWithdrawableAmount'
  | 'lockDealNFT'
  | 'name'
  | 'poolIdToTime'
  | 'provider'
  | 'registerPool'
  | 'safeFunctionCall'
  | 'setApprovedVennPolicy'
  | 'setApprovedVennPolicyFee'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'split'
  | 'supportsInterface'
  | 'withdraw';

export type SimpleBuilderFunctionName =
  | 'acceptFirewallAdmin'
  | 'buildMassPools'
  | 'firewallAdmin'
  | 'lockDealNFT'
  | 'onERC721Received'
  | 'safeFunctionCall'
  | 'setApprovedTarget'
  | 'setFirewall'
  | 'setFirewallAdmin';

export type TimedDealProviderFunctionName =
  | 'acceptFirewallAdmin'
  | 'beforeTransfer'
  | 'createNewPool'
  | 'currentParamsTargetLength'
  | 'firewallAdmin'
  | 'getParams'
  | 'getSubProvidersPoolIds'
  | 'getWithdrawableAmount'
  | 'lockDealNFT'
  | 'name'
  | 'poolIdToAmount'
  | 'poolIdToTime'
  | 'provider'
  | 'registerPool'
  | 'safeFunctionCall'
  | 'setApprovedVennPolicy'
  | 'setApprovedVennPolicyFee'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'split'
  | 'supportsInterface'
  | 'withdraw';

export type VaultManagerFunctionName =
  | 'acceptFirewallAdmin'
  | 'createNewVault'
  | 'depositByToken'
  | 'firewallAdmin'
  | 'getAllVaultBalanceByToken'
  | 'getCurrentVaultBalanceByToken'
  | 'getCurrentVaultIdByToken'
  | 'getTotalVaultsByToken'
  | 'getVaultBalanceByVaultId'
  | 'isDepositActiveForVaultId'
  | 'isWithdrawalActiveForVaultId'
  | 'nonces'
  | 'owner'
  | 'renounceOwnership'
  | 'royaltyInfo'
  | 'safeDeposit'
  | 'safeFunctionCall'
  | 'setActiveStatusForVaultId'
  | 'setApprovedTarget'
  | 'setFirewall'
  | 'setFirewallAdmin'
  | 'setTradeStartTime'
  | 'setTrustee'
  | 'supportsInterface'
  | 'tokenToVaultIds'
  | 'totalVaults'
  | 'transferOwnership'
  | 'trustee'
  | 'updateTrustee'
  | 'vaultIdToTokenAddress'
  | 'vaultIdToTradeStartTime'
  | 'vaultIdToVault'
  | 'withdrawByVaultId';

export type ContractName = 'DealProvider' | 'DispenserProvider' | 'ForceWithdraw' | 'InvestProvider' | 'LockDealNFT' | 'LockDealProvider' | 'SimpleBuilder' | 'TimedDealProvider' | 'VaultManager';

export type ContractFunctionNameMap = {
  DealProvider: DealProviderFunctionName;
  DispenserProvider: DispenserProviderFunctionName;
  ForceWithdraw: ForceWithdrawFunctionName;
  InvestProvider: InvestProviderFunctionName;
  LockDealNFT: LockDealNFTFunctionName;
  LockDealProvider: LockDealProviderFunctionName;
  SimpleBuilder: SimpleBuilderFunctionName;
  TimedDealProvider: TimedDealProviderFunctionName;
  VaultManager: VaultManagerFunctionName;
};

export type ContractFunctionName<T extends ContractName = ContractName> =
  T extends keyof ContractFunctionNameMap ? ContractFunctionNameMap[T] : never;
