name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - name: Set package version from tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=${TAG#v}
          pnpm version --no-git-tag-version "$VERSION"
      - name: Set git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com          
      - run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

